### PR TITLE
Add realtime error messages during testing

### LINKED ISSUE #52: Add real-time error messages during testing
Sometimes it is useful to have some information about your test asserts during execution, particularly in long period tests. I propose to add real-time error messages using python's logging module.

### PR DESCRIPTION
**Pull request by jaimedelreyg**
Closes #52

### CODE REVIEW

**Review by okken — COMMENTED** [review]
Interesting addition. Could you add tests for it?

**Comment by bondnotanymore** [comment]
Hi @okken 
This is an important PR for a lot of folks since it solves the incompatibility with allure-pytest plugin reports.
Can we plz expedite the merge and release new version of pytest_check soon.

https://github.com/okken/pytest-check/issues/57#issuecomment-844057194

**Comment by okken** [comment]
This PR is incomplete. 
It needs tests to check the functionality, and should cover all use cases of the plugin. 
As far as I can tell (although I may be missing something), the changes add error logging to the context manager use case.
There are other use cases, such as the fixture check.equal() and other methods, as well as the check_func use model.

I think possibly the right place to add logging.error() is within log_failure(), maybe.
Also, when looking at examples using this code or similar, the failures show up twice in the CLI report. 
I'm not sure if that's what we want.

I do agree that having pytest-check work with allure would be a good thing. 
However, the PR doesn't do that.

**Comment by okken** [comment]
I stated this at the before, but bears repeating. Tests for the new functionality need to be included in the PR.

**Comment by okken** [comment]
closing this for now, if you have desire to continue to work on it, and include tests for the additional behavior, feel free to try again.

**Pull request closed without merging**
