### PR TITLE
Add option for logging every individual failure

### PR DESCRIPTION
**Pull request by alblasco**
Thanks again for this plugin. And second PR to this repo :tada: 

Just to add an option to be able to see failures inside log as they appear

Currently you can see all the failures together in the final exception, and so every individual failure can not be related with the rest of your logging.

I have made it optional so behavior is not modified without the option.
And added new unit tests for new code

Please let me know your kind feedback.

### CODE REVIEW

**Comment by okken** [comment]
I'm glad you were able to navigate the recent refactoring of the code.
Thanks for adding tests.
I'll try to get this evaluated soon-ish.

**Comment by okken** [comment]
Or at least let me know if you think `--check-log-level` is a decent enough name, and I can make the mod. 
I've been trying on a merged branch of your change + the 2.0.0 changes. 
And it is quite fun.

**Comment by okken** [comment]
I want to make sure the changes are obviously from you. But not make lots of extra work for you.

**Comment by okken** [comment]
conflicts resolved. I'll merge this, then make the mod to --check-log-level

**Comment by okken** [comment]
But.... probably do that merge and mod tomorrow.

**Comment by okken** [comment]
ok. I've merged the changes, and I'm playing with it. 
I don't really like the log format thought, so changes are probably inevitable. 
I also want to make sure this plays nicely with other pytest logging features.

So, no promises, and stay tuned, but work ongoing.

**Comment by okken** [comment]
Also, thanks for your contribution!

**Comment by okken** [comment]
Ok. Apologies, but I merged, then wasn't happy with the current state, so reverted the merge.
I know this creates extra work, but I want to make sure it's cleaner output before merging to main.

My issue mostly is that the output when setting --check-log-level=DEBUG --log-cli-level=DEBUG is a bit weird.
I don't like that the name of the file within the check plugin shows up, that's really not important to the end user.

**Comment by okken** [comment]
Perhaps I'm missing the use case.

Second issue is that the test doesn't seem to check that the log output is present.
The no logging and logging cases in the test don't really seem different.
Am I missing something?

**Comment by okken** [comment]
I don't know how to re-open this pr. so we could work off of the "logging" branch for now, or you can re-submit a PR based on current main, if you want.
I'm still going to work on this, and I'm sorry for the churn, but I don't think it's ready yet.

**Comment by alblasco** [comment]
My feedback:
* My user case is to trace inside logs with ERROR level.
* I included check-log-level option as someone could prefer fatal or warning, but that's a minor difference that may be worthless (In any case debug level has no sense in any case). 
* If we agree on the error level then option could be just a boolean to enable or not.
* Or another possibility is even to add always (without parameter to enable it), as logging is always available, and no harm on adding a log line as behavior depends on how you have configured previously logger

Please let me know your preferences, so we can reach an agreement

**Comment by okken** [comment]
Thanks for the feedback. I have a few questions.

I guess I don't know what you mean by "inside logs". 
- Do you mean log files? 
- How are you turning those on during testing?
- Are you using `--log-file` from pytest to put them all in a single file?

Or are you using `--log-cli-level` to turn on stdout logging.
Or something completely different?

The levels aren't an issue. I used DEBUG in the example because I liked the terminal color that pytest uses for DEBUG.

The formatting issue I have is that the log messages from pytest-check look like this:
`ERROR    pytest_check.check_log:check_log.py:78 FAILURE: check ...`
- The `pytest_check.check_log:check_log.py:78` part of that log is meaningless to the end user.
- There may be no way to get rid of that other than the user specifying a `--log_cli_format` or a `--log_file_format` to remove the file name, but that seems like a problem. Is that not a problem?

I'd also like to have an example that isn't necessarily testing that `--check-log-level` works, but shows how someone could use it.

**Comment by okken** [comment]
I guess something like this is semi-useful: 
`pytest --check-log-level=ERROR  --log-cli-level=DEBUG --check-max-tb=10 --show-capture=no --log-format="%(levelname)s %(message)s"`, but that's kind of a l lot.

However, I imagine it's something you'd put into a pytest.ini file or something.

**Comment by okken** [comment]
I think I'm going to go with the hook idea.
Something like `check.set_fail_function(logging.error)` should work.
What do you think of that name, `set_fail_function()`? Maybe I'll release it as a beta feature for people to play with and give me feedback.

**Comment by okken** [comment]
Added `set_failure_callback()` as an experimental feature for 2.1.0.
Hopefully that works for your use case. 
see PR #115

**Comment by alblasco** [comment]
Yes PR #115 is fine for me.
My user case is covered using 
```
import logging
log = logging.getLogger(__name__)
check.set_failure_callback(log.error)
```

No problem with this name.

**Pull request merged**
