### PR TITLE
Copy the failures on node's item

### PR DESCRIPTION
**Pull request by abhijitmamarde**
saves failures on requests nodes item so that its available for any further processing

### CODE REVIEW

**Comment by abhijitmamarde** [comment]
Required to add this for integrating the failures into the allure reports.

**Comment by okken** [comment]
Interesting.

**Comment by okken** [comment]
any other affects?

**Comment by abhijitmamarde** [comment]
No other affects. Just adds one more variable which can be reference if required. Useful for capturing the failures and reporting in any other / custom reporting framework is used.

**Comment by abhijitmamarde** [comment]
Not sure about the checks which are reported as failed. Not seeing anything there! So could you please merge this PR ?

**Comment by okken** [comment]
Failures are intentionally stored outside of `item` because it's not the intent of this plugin to alter the structure of `item`.
For allure, see https://github.com/okken/pytest-check/issues/42#issuecomment-680064991

**Pull request closed without merging**
